# Generated by Django 3.1.7 on 2021-03-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_auto_20210305_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='ProductApp.Category'),
        ),
    ]
